#!/usr/bin/env python3
"""Generate the SQL transform that expands a wide VCF staging table into the target lr_haplotypes table.

The staging table (produced by `genohype export clickhouse`) has one Tuple column per sample,
e.g. HG002.GT, HG002.DP, HG002.GQ, HG002.RNC. This script generates an INSERT INTO ... SELECT
using arrayJoin to unpivot those into per-sample rows.

Usage:
    # With a list of samples:
    python3 development/clickhouse/generate_haplotype_transform.py HG002 HG003 HG004

    # Extract samples from a VCF header:
    zcat hprc_chr22.reformatted.vcf.gz | head -500 | grep "^#CHROM" | cut -f10- | tr '\\t' '\\n' | \\
        xargs python3 development/clickhouse/generate_haplotype_transform.py
"""
import sys
from pathlib import Path


def generate_transform_sql(samples: list[str], staging_table: str = "staging_haplotypes_raw") -> str:
    """Generate the arrayJoin SQL to expand per-sample genotype columns."""
    # Build the array of tuples: ('SAMPLE', `SAMPLE`.GT, `SAMPLE`.DP, `SAMPLE`.GQ, `SAMPLE`.RNC)
    array_tuples = []
    for s in samples:
        array_tuples.append(f"            ('{s}', `{s}`.GT, `{s}`.DP, `{s}`.GQ, `{s}`.RNC)")

    array_join_str = ",\n".join(array_tuples)

    sql = f"""-- Auto-generated by generate_haplotype_transform.py
-- Transforms {len(samples)} sample columns from staging to target format
-- Usage: clickhouse-client < development/clickhouse/haplotypes_transform.sql

INSERT INTO lr_haplotypes
SELECT
    chrom,
    position,
    sample_data.1 AS sample_id,
    strand_num AS strand,
    ref,
    alt,
    rsid,
    qual,
    filters,
    info_AF,
    info_AC,
    info_AN,
    allele_type,
    allele_length,
    gnomad_v4_match_type,
    info_AF_afr,
    info_AF_amr,
    info_AF_eas,
    info_AF_nfe,
    info_AF_sas,
    gt_alleles,
    gt_phased,
    sample_data.3 AS depth,
    sample_data.4 AS genotype_quality
FROM (
    SELECT
        `locus`.`contig` AS chrom,
        `locus`.`position` AS position,
        `alleles`[1] AS ref,
        `alleles`[2] AS alt,
        rsid,
        qual,
        filters,
        `info`.`AF`[1] AS info_AF,
        `info`.`AC` AS info_AC,
        `info`.`AN` AS info_AN,
        `info`.`allele_type` AS allele_type,
        `info`.`allele_length` AS allele_length,
        `info`.`gnomAD_V4_match_type` AS gnomad_v4_match_type,
        `info`.`AF_afr` AS info_AF_afr,
        `info`.`AF_amr` AS info_AF_amr,
        `info`.`AF_eas` AS info_AF_eas,
        `info`.`AF_nfe` AS info_AF_nfe,
        `info`.`AF_sas` AS info_AF_sas,
        sample_data,
        -- Split phased genotypes into separate strand rows
        -- For '1|1' -> strand 1 and strand 2; for '0|1' -> strand 2 only; for '1|0' -> strand 1 only
        arrayJoin(
            multiIf(
                sample_data.2 IN ('1|1', '1/1'), [1, 2],
                sample_data.2 IN ('1|0', '1/0'), [1],
                sample_data.2 IN ('0|1', '0/1'), [2],
                [1]  -- fallback for other non-ref genotypes
            )
        ) AS strand_num,
        -- Extract allele indices from GT string
        [] AS gt_alleles,
        position(sample_data.2, '|') > 0 AS gt_phased
    FROM (
        SELECT *,
            arrayJoin([
{array_join_str}
            ]) AS sample_data
        FROM {staging_table}
    )
)
WHERE sample_data.2 NOT IN ('0/0', '0|0', './.', '.|.');
"""
    return sql


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_haplotype_transform.py SAMPLE1 SAMPLE2 ...")
        print("       Or pipe sample names from VCF header")
        sys.exit(1)

    samples = sys.argv[1:]
    sql = generate_transform_sql(samples)

    output_path = Path(__file__).parent / "haplotypes_transform.sql"
    output_path.write_text(sql)
    print(f"Generated {output_path} with {len(samples)} samples")


if __name__ == "__main__":
    main()
