export const tableConfig = (onHeaderClick) => ({
  fields: [

    // {
    //   dataKey: 'chr',
    //   title: 'Chrom',
    //   dataType: 'integer',
    //   width: 20,
    //   onHeaderClick,
    // },
    // {
    //   dataKey: 'pos',
    //   title: 'Position',
    //   dataType: 'integer',
    //   width: 80,
    //   onHeaderClick,
    // },
    // {
    //   dataKey: 'ref',
    //   title: 'Ref',
    //   dataType: 'string',
    //   width: 20,
    //   onHeaderClick,
    // },
    // {
    //   dataKey: 'alt',
    //   title: 'Alt',
    //   dataType: 'string',
    //   width: 20,
    //   onHeaderClick,
    // },
    {
      dataKey: 'variantId',
      title: 'Variant Id ________________________________',
      dataType: 'variantId',
      width: 120,
      onHeaderClick,
    },
    {
      dataKey: 'AC',
      title: 'AC total',
      dataType: 'integer',
      width: 30,
      onHeaderClick,
    },
    { dataKey: 'AF', title: 'AF total', dataType: 'float', onHeaderClick, width: 30 },
    { dataKey: 'AC_cases', title: 'AC cases', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_ctrls', title: 'AC ctrls', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_UK_cases', title: 'UK cases', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_UK_ctrls', title: 'UK ctrls', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_FIN_cases', title: 'FIN cases', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_FIN_ctrls', title: 'FIN ctrls', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_SWE_cases', title: 'SWE cases', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'AC_SWE_ctrls', title: 'SWE ctrls', dataType: 'integer', onHeaderClick, width: 13 },
    { dataKey: 'transcriptConsequenceTerms', title: 'major transcript consequence', dataType: 'string', onHeaderClick, width: 160 },
  ],
})
