#  - Disables non-security update PRs (by setting pull requests limit to 0)
#  - Schedules security update PRs weekly
#  - Auto assigns PRs to the gnomad-browser team

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    reviewers:
      - 'broadinstitute/gnomad-browser'
  - package-ecosystem: 'pip'
    directory: '/deploy/dockerfiles/blog'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    reviewers:
      - 'broadinstitute/gnomad-browser'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    reviewers:
      - 'broadinstitute/gnomad-browser'
  - package-ecosystem: 'pip'
    directory: '/deploy/deployctl'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    reviewers:
      - 'broadinstitute/gnomad-browser'
  - package-ecosystem: 'pip'
    directory: '/data-pipeline'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    reviewers:
      - 'broadinstitute/gnomad-browser'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    reviewers:
      - 'broadinstitute/gnomad-browser'
