---
exclude: '\.snap$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.0.5 # This should be kept in sync with the version in package.json
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 22.3.0 # This should be kept in sync with the version in requirements-dev.txt
    hooks:
      - id: black
        language_version: python3
        types: [python]
  - repo: local
    hooks:
      - id: git-secrets pre-commit
        name: git-secrets (pre-commit/push hook)
        entry: git-secrets --pre_commit_hook --
        language: system
        stages: [commit, push]
      - id: git-secrets commit-msg
        name: git-secrets (commit-msg hook)
        entry: git-secrets --commit_msg_hook --
        language: system
        stages: [commit-msg]
      - id: git-secrets prepare-commit-msg
        name: git-secrets (prepare-commit-msg hook)
        entry: git-secrets --prepare_commit_msg_hook --
        language: system
        stages: [prepare-commit-msg]
