export const tissueLabels = {
  adiposeSubcutaneous: 'Adipose subcutaneous',
  adiposeVisceralOmentum: 'Adipose visceral omentum',
  adrenalGland: 'Adrenal gland',
  arteryAorta: 'Artery aorta',
  arteryCoronary: 'Artery coronary',
  arteryTibial: 'Artery tibial',
  bladder: 'Bladder',
  brainAmygdala: 'Brain amygdala',
  brainAnteriorcingulatecortexBa24: 'Brain anteriorcingulatecortex ba24',
  brainCaudateBasalganglia: 'Brain caudate basalganglia',
  brainCerebellarhemisphere: 'Brain cerebellarhemisphere',
  brainCerebellum: 'Brain cerebellum',
  brainCortex: 'Brain cortex',
  brainFrontalcortexBa9: 'Brain frontalcortex ba9',
  brainHippocampus: 'Brain hippocampus',
  brainHypothalamus: 'Brain hypothalamus',
  brainNucleusaccumbensBasalganglia: 'Brain nucleusaccumbens basalganglia',
  brainPutamenBasalganglia: 'Brain putamen basalganglia',
  brainSpinalcordCervicalc1: 'Brain spinalcord cervical c1',
  brainSubstantianigra: 'Brain substantianigra',
  breastMammarytissue: 'Breast mammarytissue',
  cellsEbvTransformedlymphocytes: 'Cells ebv transformedlymphocytes',
  cellsTransformedfibroblasts: 'Cells transformedfibroblasts',
  cervixEctocervix: 'Cervix ectocervix',
  cervixEndocervix: 'Cervix endocervix',
  colonSigmoid: 'Colon sigmoid',
  colonTransverse: 'Colon transverse',
  esophagusGastroesophagealjunction: 'Esophagus gastroesophagealjunction',
  esophagusMucosa: 'Esophagus mucosa',
  esophagusMuscularis: 'Esophagus muscularis',
  fallopianTube: 'Fallopian tube',
  heartAtrialappendage: 'Heart atrialappendage',
  heartLeftventricle: 'Heart leftventricle',
  kidneyCortex: 'Kidney cortex',
  liver: 'Liver',
  lung: 'Lung',
  minorSalivaryGland: 'Minor salivary gland',
  muscleSkeletal: 'Muscle skeletal',
  nerveTibial: 'Nerve tibial',
  ovary: 'Ovary',
  pancreas: 'Pancreas',
  pituitary: 'Pituitary',
  prostate: 'Prostate',
  skinNotsunexposedSuprapubic: 'Skin notsunexposed suprapubic',
  skinSunexposedLowerleg: 'Skin sunexposed lowerleg',
  smallIntestineTerminalileum: 'Small intestine terminalileum',
  spleen: 'Spleen',
  stomach: 'Stomach',
  testis: 'Testis',
  thyroid: 'Thyroid',
  uterus: 'Uterus',
  vagina: 'Vagina',
  wholeBlood: 'Whole blood',
}
