export const gnomadExportCsvTranslations = {
  'variant_id': 'VARIANT ID',
  'rsid': 'RSID',
  'allele_count': 'AC',
  'allele_num': 'AN',
  'allele_freq': 'AF',
  'hom_count': 'Hom',
  'hemi_count': 'Hemi',
  'consequence': 'CONSEQUENCE',
  'hgvsp': 'HGVSP',
  'hgvsc': 'HGVSC',
  'segdup': 'SEGDUP',
  'lcr': 'LCR',
  'filters': 'FILTERS',
  'xpos': 'XPOS',
  'lof': 'LOF',

  'popmax': 'POPMAX',
  'popmax_ac': 'AC_POPMAX',
  'popmax_an': 'AN_POPMAX',
  'popmax_af': 'AF_POPMAX',

  'pop_acs_african': 'AC_AFR',
  'pop_acs_latino': 'AC_AMR',
  'pop_acs_ashkenazi_jewish': 'AC_ASJ',
  'pop_acs_east_asian': 'AC_EAS',
  'pop_acs_european_finnish': 'AC_FIN',
  'pop_acs_european_non_finnish': 'AC_NFE',
  'pop_acs_other': 'AC_OTH',
  'pop_acs_south_asian': 'AC_SAS',

  'pop_ans_african': 'AN_AFR',
  'pop_ans_latino': 'AN_AMR',
  'pop_ans_ashkenazi_jewish': 'AN_ASJ',
  'pop_ans_east_asian': 'AN_EAS',
  'pop_ans_european_finnish': 'AN_FIN',
  'pop_ans_european_non_finnish': 'AN_NFE',
  'pop_ans_other': 'AN_OTH',
  'pop_ans_south_asian': 'AN_SAS',

  'pop_homs_african': 'Hom_AFR',
  'pop_homs_latino': 'Hom_AMR',
  'pop_homs_ashkenazi_jewish': 'Hom_ASJ',
  'pop_homs_east_asian': 'Hom_EAS',
  'pop_homs_european_finnish': 'Hom_FIN',
  'pop_homs_european_non_finnish': 'Hom_NFE',
  'pop_homs_other': 'Hom_OTH',
  'pop_homs_south_asian': 'Hom_SAS',

  'pop_hemi_african': 'Hemi_AFR',
  'pop_hemi_latino': 'Hemi_AMR',
  'pop_hemi_ashkenazi_jewish': 'Hemi_ASJ',
  'pop_hemi_east_asian': 'Hemi_EAS',
  'pop_hemi_european_finnish': 'Hemi_FIN',
  'pop_hemi_european_non_finnish': 'Hemi_NFE',
  'pop_hemi_other': 'Hemi_OTH',
  'pop_hemi_south_asian': 'Hemi_SAS',

  'quality_metrics_MQ': 'MQ',
  'quality_metrics_DP_MEDIAN': 'DP_MEDIAN',
  'quality_metrics_ClippingRankSum': 'ClippingRankSum',
  'quality_metrics_GQ_MEDIAN': 'GQ_MEDIAN',
  'quality_metrics_VQSLOD': 'VQSLOD',
  'quality_metrics_AS_RF': 'AS_RF',
  'quality_metrics_DP': 'DP',
  'quality_metrics_FS': 'FS',
  'quality_metrics_InbreedingCoeff': 'InbreedingCoeff',
  'quality_metrics_AB_MEDIAN': 'AB_MEDIAN',
  'quality_metrics_QD': 'QD',
  'quality_metrics_BaseQRankSum': 'BaseQRankSum',
  'quality_metrics_ReadPosRankSum': 'ReadPosRankSum',
  'quality_metrics_DREF_MEDIAN': 'DREF_MEDIAN',
  'quality_metrics_MQRankSum': 'MQRankSum',
}
