/* eslint-disable quote-props */

export const vcfFields = [
  'AC',
  'AF',
  'AN',
  'BaseQRankSum',
  'ClippingRankSum',
  'DB',
  'DP',
  'FS',
  'InbreedingCoeff',
  'MQ',
  'MQRankSum',
  'QD',
  'ReadPosRankSum',
  'SOR',
  'VQSLOD',
  'VQSR_culprit',
  'VQSR_NEGATIVE_TRAIN_SITE',
  'VQSR_POSITIVE_TRAIN_SITE',
  'GQ_HIST_ALT',
  'DP_HIST_ALT',
  'AB_HIST_ALT',
  'GQ_HIST_ALL',
  'DP_HIST_ALL',
  'AB_HIST_ALL',
  'AC_AFR_Male',
  'AC_AMR_Male',
  'AC_ASJ_Male',
  'AC_EAS_Male',
  'AC_FIN_Male',
  'AC_NFE_Male',
  'AC_OTH_Male',
  'AC_Male',
  'AC_AFR_Female',
  'AC_AMR_Female',
  'AC_ASJ_Female',
  'AC_EAS_Female',
  'AC_FIN_Female',
  'AC_NFE_Female',
  'AC_OTH_Female',
  'AC_Female',
  'AN_AFR_Male',
  'AN_AMR_Male',
  'AN_ASJ_Male',
  'AN_EAS_Male',
  'AN_FIN_Male',
  'AN_NFE_Male',
  'AN_OTH_Male',
  'AN_Male',
  'AN_AFR_Female',
  'AN_AMR_Female',
  'AN_ASJ_Female',
  'AN_EAS_Female',
  'AN_FIN_Female',
  'AN_NFE_Female',
  'AN_OTH_Female',
  'AN_Female',
  'AF_AFR_Male',
  'AF_AMR_Male',
  'AF_ASJ_Male',
  'AF_EAS_Male',
  'AF_FIN_Male',
  'AF_NFE_Male',
  'AF_OTH_Male',
  'AF_Male',
  'AF_AFR_Female',
  'AF_AMR_Female',
  'AF_ASJ_Female',
  'AF_EAS_Female',
  'AF_FIN_Female',
  'AF_NFE_Female',
  'AF_OTH_Female',
  'AF_Female',
  'GC_AFR_Male',
  'GC_AMR_Male',
  'GC_ASJ_Male',
  'GC_EAS_Male',
  'GC_FIN_Male',
  'GC_NFE_Male',
  'GC_OTH_Male',
  'GC_Male',
  'GC_AFR_Female',
  'GC_AMR_Female',
  'GC_ASJ_Female',
  'GC_EAS_Female',
  'GC_FIN_Female',
  'GC_NFE_Female',
  'GC_OTH_Female',
  'GC_Female',
  'GC_raw',
  'AC_raw',
  'AN_raw',
  'GC',
  'AF_raw',
  'Hom_AFR',
  'Hemi_AFR',
  'Hom_AMR',
  'Hemi_AMR',
  'Hom_ASJ',
  'Hemi_ASJ',
  'Hom_EAS',
  'Hemi_EAS',
  'Hom_FIN',
  'Hemi_FIN',
  'Hom_NFE',
  'Hemi_NFE',
  'Hom_OTH',
  'Hemi_OTH',
  'Hom',
  'Hemi',
  'Hom_raw',
  'Hemi_raw',
  'AC_AFR',
  'AC_AMR',
  'AC_ASJ',
  'AC_EAS',
  'AC_FIN',
  'AC_NFE',
  'AC_OTH',
  'AN_AFR',
  'AN_AMR',
  'AN_ASJ',
  'AN_EAS',
  'AN_FIN',
  'AN_NFE',
  'AN_OTH',
  'AF_AFR',
  'AF_AMR',
  'AF_ASJ',
  'AF_EAS',
  'AF_FIN',
  'AF_NFE',
  'AF_OTH',
  'STAR_AC',
  'STAR_AC_raw',
  'STAR_Hom',
  'STAR_Hemi',
  'POPMAX',
  'AC_POPMAX',
  'AN_POPMAX',
  'AF_POPMAX',
  'DP_MEDIAN',
  'DREF_MEDIAN',
  'GQ_MEDIAN',
  'AB_MEDIAN',
  'AS_RF',
  'AS_FilterStatus',
  'AS_RF_POSITIVE_TRAIN',
  'AS_RF_NEGATIVE_TRAIN',
  'segdup',
  'lcr',
]

export const gnomadExportCsvTranslations = {
  'variant_id': 'VARIANT ID',
  'rsid': 'RSID',
  'allele_count': 'AC',
  'allele_num': 'AN',
  'allele_freq': 'AF',
  'hom_count': 'Hom',
  'hemi_count': 'Hemi',
  'consequence': 'CONSEQUENCE',
  'hgvsp': 'HGVSP',
  'hgvsc': 'HGVSC',
  'segdup': 'SEGDUP',
  'lcr': 'LCR',
  'filters': 'FILTERS',
  'xpos': 'XPOS',
  'lof': 'LOF',

  'popmax': 'POPMAX',
  'popmax_ac': 'AC_POPMAX',
  'popmax_an': 'AN_POPMAX',
  'popmax_af': 'AF_POPMAX',

  'pop_acs_african': 'AC_AFR',
  'pop_acs_latino': 'AC_AMR',
  'pop_acs_ashkenazi_jewish': 'AC_ASJ',
  'pop_acs_east_asian': 'AC_EAS',
  'pop_acs_european_finnish': 'AC_FIN',
  'pop_acs_european_non_finnish': 'AC_NFE',
  'pop_acs_other': 'AC_OTH',
  'pop_acs_south_asian': 'AC_SAS',

  'pop_ans_african': 'AN_AFR',
  'pop_ans_latino': 'AN_AMR',
  'pop_ans_ashkenazi_jewish': 'AN_ASJ',
  'pop_ans_east_asian': 'AN_EAS',
  'pop_ans_european_finnish': 'AN_FIN',
  'pop_ans_european_non_finnish': 'AN_NFE',
  'pop_ans_other': 'AN_OTH',
  'pop_ans_south_asian': 'AN_SAS',

  'pop_homs_african': 'Hom_AFR',
  'pop_homs_latino': 'Hom_AMR',
  'pop_homs_ashkenazi_jewish': 'Hom_ASJ',
  'pop_homs_east_asian': 'Hom_EAS',
  'pop_homs_european_finnish': 'Hom_FIN',
  'pop_homs_european_non_finnish': 'Hom_NFE',
  'pop_homs_other': 'Hom_OTH',
  'pop_homs_south_asian': 'Hom_SAS',

  'pop_hemi_african': 'Hemi_AFR',
  'pop_hemi_latino': 'Hemi_AMR',
  'pop_hemi_ashkenazi_jewish': 'Hemi_ASJ',
  'pop_hemi_east_asian': 'Hemi_EAS',
  'pop_hemi_european_finnish': 'Hemi_FIN',
  'pop_hemi_european_non_finnish': 'Hemi_NFE',
  'pop_hemi_other': 'Hemi_OTH',
  'pop_hemi_south_asian': 'Hemi_SAS',

  'quality_metrics_MQ': 'MQ',
  'quality_metrics_DP_MEDIAN': 'DP_MEDIAN',
  'quality_metrics_ClippingRankSum': 'ClippingRankSum',
  'quality_metrics_GQ_MEDIAN': 'GQ_MEDIAN',
  'quality_metrics_VQSLOD': 'VQSLOD',
  'quality_metrics_AS_RF': 'AS_RF',
  'quality_metrics_DP': 'DP',
  'quality_metrics_FS': 'FS',
  'quality_metrics_InbreedingCoeff': 'InbreedingCoeff',
  'quality_metrics_AB_MEDIAN': 'AB_MEDIAN',
  'quality_metrics_QD': 'QD',
  'quality_metrics_BaseQRankSum': 'BaseQRankSum',
  'quality_metrics_ReadPosRankSum': 'ReadPosRankSum',
  'quality_metrics_DREF_MEDIAN': 'DREF_MEDIAN',
  'quality_metrics_MQRankSum': 'MQRankSum',
}
// originalAltAlleles
// exon
// transcriptIds
// fitted_score
