---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi25-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      name: epi25-browser
  template:
    metadata:
      labels:
        name: epi25-browser
    spec:
      containers:
      - name: epi25-browser
        image: gcr.io/exac-gnomad/epi25-browser
        env:
        - name: ELASTICSEARCH_URL
          value: elasticsearch:9200
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
