---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gnomad-d-serve
  labels:
    state: serving
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-d-serve
  template:
    metadata:
      labels:
        name: gnomad-d-serve
    spec:
      containers:
      - name: gnomad-d-serve
        image: gcr.io/exac-gnomad/gnomad-browser-beta
        ports:
        - containerPort: 80
