---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gnomad-p-serve
  labels:
    state: serving
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gnomad-p-serve
  template:
    metadata:
      labels:
        name: gnomad-p-serve
    spec:
      containers:
      - name: gnomad-p-serve
        image: gcr.io/exac-gnomad/gnomad-browser-beta
        env:
        - name: ENABLE_SSL_REDIRECT
          value: "true"
        ports:
        - containerPort: 80
