export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'

export const SET_CURRENT_GENE = 'SET_CURRENT_GENE'

export const REQUEST_GENE_DATA = 'REQUEST_GENE_DATA'
export const RECEIVE_GENE_DATA = 'RECEIVE_GENE_DATA'
