export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'

export const SET_CURRENT_GENE = 'SET_CURRENT_GENE'
export const SET_CURRENT_VARIANT = 'SET_CURRENT_VARIANT'
export const SET_NAVIGATION_POSITION = 'SET_NAVIGATION_POSITION'

export const REQUEST_GENE_DATA = 'REQUEST_GENE_DATA'
export const RECEIVE_GENE_DATA = 'RECEIVE_GENE_DATA'

export const REQUEST_REGION_DATA = 'REQUEST_REGION_DATA'
export const RECEIVE_REGION_DATA = 'RECEIVE_REGION_DATA'

export const SET_VARIANT_SORT = 'SET_VARIANT_SORT'
export const SET_VISIBLE_IN_TABLE = 'UPDATE_VISIBLE_IN_TABLE'
