export const GTEX_TISSUE_NAMES = [
  'Adipose - Subcutaneous',
  'Adipose - Visceral (Omentum)',
  'Adrenal Gland',
  'Artery - Aorta',
  'Artery - Coronary',
  'Artery - Tibial',
  'Bladder',
  'Brain - Amygdala',
  'Brain - Anterior cingulate cortex (BA24)',
  'Brain - Caudate (basal ganglia)',
  'Brain - Cerebellar Hemisphere',
  'Brain - Cerebellum',
  'Brain - Cortex',
  'Brain - Frontal Cortex (BA9)',
  'Brain - Hippocampus',
  'Brain - Hypothalamus',
  'Brain - Nucleus accumbens (basal ganglia)',
  'Brain - Putamen (basal ganglia)',
  'Brain - Spinal cord (cervical c-1)',
  'Brain - Substantia nigra',
  'Breast - Mammary Tissue',
  'Cells - EBV-transformed lymphocytes',
  'Cells - Transformed fibroblasts',
  'Cervix - Ectocervix',
  'Cervix - Endocervix',
  'Colon - Sigmoid',
  'Colon - Transverse',
  'Esophagus - Gastroesophageal Junction',
  'Esophagus - Mucosa',
  'Esophagus - Muscularis',
  'Fallopian Tube',
  'Heart - Atrial Appendage',
  'Heart - Left Ventricle',
  'Kidney - Cortex',
  'Liver',
  'Lung',
  'Minor Salivary Gland',
  'Muscle - Skeletal',
  'Nerve - Tibial',
  'Ovary',
  'Pancreas',
  'Pituitary',
  'Prostate',
  'Skin - Not Sun Exposed (Suprapubic)',
  'Skin - Sun Exposed (Lower leg)',
  'Small Intestine - Terminal Ileum',
  'Spleen',
  'Stomach',
  'Testis',
  'Thyroid',
  'Uterus',
  'Vagina',
  'Whole Blood',
]

export const GTEX_TISSUE_COLORS = {
  'Adipose - Subcutaneous': '#FF6600',
  'Adipose - Visceral (Omentum)': '#FFAA00',
  'Adrenal Gland': '#33DD33',
  'Artery - Aorta': '#FF5555',
  'Artery - Coronary': '#FFAA99',
  'Artery - Tibial': '#FF0000',
  Bladder: '#AA0000',
  'Brain - Amygdala': '#EEEE00',
  'Brain - Anterior cingulate cortex (BA24)': '#EEEE00',
  'Brain - Caudate (basal ganglia)': '#EEEE00',
  'Brain - Cerebellar Hemisphere': '#EEEE00',
  'Brain - Cerebellum': '#EEEE00',
  'Brain - Cortex': '#EEEE00',
  'Brain - Frontal Cortex (BA9)': '#EEEE00',
  'Brain - Hippocampus': '#EEEE00',
  'Brain - Hypothalamus': '#EEEE00',
  'Brain - Nucleus accumbens (basal ganglia)': '#EEEE00',
  'Brain - Putamen (basal ganglia)': '#EEEE00',
  'Brain - Spinal cord (cervical c-1)': '#EEEE00',
  'Brain - Substantia nigra': '#EEEE00',
  'Breast - Mammary Tissue': '#33CCCC',
  'Cells - EBV-transformed lymphocytes': '#CC66FF',
  'Cells - Transformed fibroblasts': '#AAEEFF',
  'Cervix - Ectocervix': '#FFCCCC',
  'Cervix - Endocervix': '#CCAADD',
  'Colon - Sigmoid': '#EEBB77',
  'Colon - Transverse': '#CC9955',
  'Esophagus - Gastroesophageal Junction': '#8B7355',
  'Esophagus - Mucosa': '#552200',
  'Esophagus - Muscularis': '#BB9988',
  'Fallopian Tube': '#FFCCCC',
  'Heart - Atrial Appendage': '#9900FF',
  'Heart - Left Ventricle': '#660099',
  'Kidney - Cortex': '#22FFDD',
  Liver: '#AABB66',
  Lung: '#99FF00',
  'Minor Salivary Gland': '#99BB88',
  'Muscle - Skeletal': '#AAAAFF',
  'Nerve - Tibial': '#FFD700',
  Ovary: '#FFAAFF',
  Pancreas: '#995522',
  Pituitary: '#AAFF99',
  Prostate: '#DDDDDD',
  'Skin - Not Sun Exposed (Suprapubic)': '#0000FF',
  'Skin - Sun Exposed (Lower leg)': '#7777FF',
  'Small Intestine - Terminal Ileum': '#555522',
  Spleen: '#778855',
  Stomach: '#FFDD99',
  Testis: '#AAAAAA',
  Thyroid: '#006600',
  Uterus: '#FF66FF',
  Vagina: '#FF5599',
  'Whole Blood': '#FF00BB',
}
