export const GTEX_TISSUE_NAMES = {
  adipose_subcutaneous: 'Adipose - Subcutaneous',
  adipose_visceral_omentum: 'Adipose - Visceral (Omentum)',
  adrenal_gland: 'Adrenal Gland',
  artery_aorta: 'Artery - Aorta',
  artery_coronary: 'Artery - Coronary',
  artery_tibial: 'Artery - Tibial',
  bladder: 'Bladder',
  brain_amygdala: 'Brain - Amygdala',
  brain_anterior_cingulate_cortex_ba24: 'Brain - Anterior cingulate cortex (BA24)',
  brain_caudate_basal_ganglia: 'Brain - Caudate (basal ganglia)',
  brain_cerebellar_hemisphere: 'Brain - Cerebellar Hemisphere',
  brain_cerebellum: 'Brain - Cerebellum',
  brain_cortex: 'Brain - Cortex',
  brain_frontal_cortex_ba9: 'Brain - Frontal Cortex (BA9)',
  brain_hippocampus: 'Brain - Hippocampus',
  brain_hypothalamus: 'Brain - Hypothalamus',
  brain_nucleus_accumbens_basal_ganglia: 'Brain - Nucleus accumbens (basal ganglia)',
  brain_putamen_basal_ganglia: 'Brain - Putamen (basal ganglia)',
  brain_spinal_cord_cervical_c_1: 'Brain - Spinal cord (cervical c-1)',
  brain_substantia_nigra: 'Brain - Substantia nigra',
  breast_mammary_tissue: 'Breast - Mammary Tissue',
  cells_ebv_transformed_lymphocytes: 'Cells - EBV-transformed lymphocytes',
  cells_transformed_fibroblasts: 'Cells - Transformed fibroblasts',
  cervix_ectocervix: 'Cervix - Ectocervix',
  cervix_endocervix: 'Cervix - Endocervix',
  colon_sigmoid: 'Colon - Sigmoid',
  colon_transverse: 'Colon - Transverse',
  esophagus_gastroesophageal_junction: 'Esophagus - Gastroesophageal Junction',
  esophagus_mucosa: 'Esophagus - Mucosa',
  esophagus_muscularis: 'Esophagus - Muscularis',
  fallopian_tube: 'Fallopian Tube',
  heart_atrial_appendage: 'Heart - Atrial Appendage',
  heart_left_ventricle: 'Heart - Left Ventricle',
  kidney_cortex: 'Kidney - Cortex',
  liver: 'Liver',
  lung: 'Lung',
  minor_salivary_gland: 'Minor Salivary Gland',
  muscle_skeletal: 'Muscle - Skeletal',
  nerve_tibial: 'Nerve - Tibial',
  ovary: 'Ovary',
  pancreas: 'Pancreas',
  pituitary: 'Pituitary',
  prostate: 'Prostate',
  skin_not_sun_exposed_suprapubic: 'Skin - Not Sun Exposed (Suprapubic)',
  skin_sun_exposed_lower_leg: 'Skin - Sun Exposed (Lower leg)',
  small_intestine_terminal_ileum: 'Small Intestine - Terminal Ileum',
  spleen: 'Spleen',
  stomach: 'Stomach',
  testis: 'Testis',
  thyroid: 'Thyroid',
  uterus: 'Uterus',
  vagina: 'Vagina',
  whole_blood: 'Whole Blood',
}
