apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.deployment.yaml
  - ./api.service.yaml
  - ./api.serviceaccount.yaml
  - ./browser.deployment.yaml
configurations:
  - ./add-suffix.yaml
