---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  labels:
    app: opentelemetry-collector
spec:
  selector:
    app: opentelemetry-collector
  ports:
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp-http
  type: ClusterIP
