# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - stylecheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - gocritic
    - revive
    - misspell
    - unparam
    - prealloc
    - unconvert
    - cyclop
    - gocyclo
    - gocognit
    - godot
    - godox
    - dupl
    - funlen
    - whitespace
    - wsl
    - goprintffuncname
    - nilerr
    - exhaustive
    - sqlclosecheck
    - noctx
    - bodyclose

  disable:
    - depguard
    - dogsled
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - err113
    - lll
    - nakedret
    - nlreturn
    - nolintlint
    - rowserrcheck
    - testpackage
    - wrapcheck

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: gnomad-browser/gnomad-go-api
  
  govet:
    enable:
      - shadow
  
  revive:
    confidence: 0.8
  
  staticcheck:
    # Ensure all checks are enabled, including ST1003 (naming conventions)
    checks: ["all"]
  
  stylecheck:
    # Ensure all checks are enabled, including ST1003 (naming conventions)
    checks: ["all", "-ST1000", "-ST1020", "-ST1021", "-ST1022"]
    # ST1000: at least one file in a package should have a package comment
    # ST1020-ST1022: documentation comment checks (we'll keep these disabled for now)
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  funlen:
    lines: 100
    statements: 60
  
  cyclop:
    max-complexity: 15
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20

issues:
  exclude-dirs:
    - internal/graph/generated.go
    - internal/graph/model/models_gen.go
  
  exclude-rules:
    # Exclude generated files
    - path: _gen\.go$
      linters:
        - all
    
    # Exclude test files from some linters
    - path: _test\.go$
      linters:
        - dupl
        - funlen
        - gocognit
        - gocyclo
    
    # Exclude specific files
    - path: internal/graph/generated.go
      linters:
        - all
    
    - path: internal/graph/model/models_gen.go
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0