---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      name: schema-browser
  template:
    metadata:
      labels:
        name: schema-browser
    spec:
      containers:
      - name: schema-browser
        image: gcr.io/exac-gnomad/schema-browser
        env:
        - name: MONGO_URL
          value: mongodb://gnomad-mongo:27017/exac
        - name: ELASTICSEARCH_URL
          value: elasticsearch:9200
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
