---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asc-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      name: asc-browser
  template:
    metadata:
      labels:
        name: asc-browser
    spec:
      containers:
      - name: asc-browser
        image: gcr.io/exac-gnomad/asc-browser
        env:
        - name: ELASTICSEARCH_URL
          value: elasticsearch:9200
        - name: PORT
          value: "80"
        - name: MAX_CONCURRENT_ES_REQUESTS
          value: "100"
        - name: MAX_QUEUED_ES_REQUESTS
          value: "1000"
        ports:
        - containerPort: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
