export const haplogroups = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'HV',
  'I',
  'J',
  'K',
  'L0',
  'L1',
  'L2',
  'L3',
  'L4',
  'L5',
  'M',
  'N',
  'P',
  'R',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
] as const

export type Haplogroup = typeof haplogroups[number]

export const codeToAncestryName = {
  afr: 'African/African American',
  ami: 'Amish',
  amr: 'Latino/Admixed American',
  asj: 'Ashkenazi Jewish',
  eas: 'East Asian',
  fin: 'European (Finnish)',
  mid: 'Middle Eastern',
  nfe: 'European (non-Finnish)',
  oth: 'Other',
  sas: 'South Asian',
} as const

type AncestryCode = keyof typeof codeToAncestryName
export type AncestryName = typeof codeToAncestryName[AncestryCode]

export interface MtdnaHaplogroupSampleCount {
  haplogroup: Haplogroup
  ancestry: AncestryCode
  n: number
}

const mtdnaHaplogroupSampleData: MtdnaHaplogroupSampleCount[] = [
  { haplogroup: 'A', ancestry: 'afr', n: 94 },
  { haplogroup: 'A', ancestry: 'amr', n: 2380 },
  { haplogroup: 'A', ancestry: 'eas', n: 74 },
  { haplogroup: 'A', ancestry: 'nfe', n: 43 },
  { haplogroup: 'A', ancestry: 'oth', n: 84 },
  { haplogroup: 'A', ancestry: 'sas', n: 5 },
  { haplogroup: 'B', ancestry: 'afr', n: 95 },
  { haplogroup: 'B', ancestry: 'amr', n: 1178 },
  { haplogroup: 'B', ancestry: 'eas', n: 208 },
  { haplogroup: 'B', ancestry: 'nfe', n: 22 },
  { haplogroup: 'B', ancestry: 'oth', n: 32 },
  { haplogroup: 'B', ancestry: 'sas', n: 2 },
  { haplogroup: 'C', ancestry: 'afr', n: 53 },
  { haplogroup: 'C', ancestry: 'amr', n: 687 },
  { haplogroup: 'C', ancestry: 'eas', n: 47 },
  { haplogroup: 'C', ancestry: 'nfe', n: 37 },
  { haplogroup: 'C', ancestry: 'oth', n: 39 },
  { haplogroup: 'C', ancestry: 'sas', n: 5 },
  { haplogroup: 'D', ancestry: 'afr', n: 37 },
  { haplogroup: 'D', ancestry: 'amr', n: 182 },
  { haplogroup: 'D', ancestry: 'eas', n: 309 },
  { haplogroup: 'D', ancestry: 'fin', n: 12 },
  { haplogroup: 'D', ancestry: 'nfe', n: 29 },
  { haplogroup: 'D', ancestry: 'oth', n: 12 },
  { haplogroup: 'D', ancestry: 'sas', n: 22 },
  { haplogroup: 'E', ancestry: 'afr', n: 11 },
  { haplogroup: 'E', ancestry: 'amr', n: 2 },
  { haplogroup: 'E', ancestry: 'eas', n: 11 },
  { haplogroup: 'E', ancestry: 'nfe', n: 4 },
  { haplogroup: 'E', ancestry: 'oth', n: 6 },
  { haplogroup: 'F', ancestry: 'afr', n: 21 },
  { haplogroup: 'F', ancestry: 'amr', n: 3 },
  { haplogroup: 'F', ancestry: 'eas', n: 229 },
  { haplogroup: 'F', ancestry: 'nfe', n: 6 },
  { haplogroup: 'F', ancestry: 'sas', n: 23 },
  { haplogroup: 'G', ancestry: 'afr', n: 1 },
  { haplogroup: 'G', ancestry: 'eas', n: 60 },
  { haplogroup: 'G', ancestry: 'fin', n: 5 },
  { haplogroup: 'G', ancestry: 'nfe', n: 17 },
  { haplogroup: 'G', ancestry: 'sas', n: 8 },
  { haplogroup: 'H', ancestry: 'afr', n: 306 },
  { haplogroup: 'H', ancestry: 'ami', n: 164 },
  { haplogroup: 'H', ancestry: 'amr', n: 329 },
  { haplogroup: 'H', ancestry: 'asj', n: 357 },
  { haplogroup: 'H', ancestry: 'eas', n: 1 },
  { haplogroup: 'H', ancestry: 'fin', n: 2198 },
  { haplogroup: 'H', ancestry: 'mid', n: 5 },
  { haplogroup: 'H', ancestry: 'nfe', n: 11226 },
  { haplogroup: 'H', ancestry: 'oth', n: 152 },
  { haplogroup: 'H', ancestry: 'sas', n: 46 },
  { haplogroup: 'HV', ancestry: 'afr', n: 9 },
  { haplogroup: 'HV', ancestry: 'amr', n: 10 },
  { haplogroup: 'HV', ancestry: 'asj', n: 68 },
  { haplogroup: 'HV', ancestry: 'fin', n: 18 },
  { haplogroup: 'HV', ancestry: 'mid', n: 2 },
  { haplogroup: 'HV', ancestry: 'nfe', n: 546 },
  { haplogroup: 'HV', ancestry: 'oth', n: 6 },
  { haplogroup: 'HV', ancestry: 'sas', n: 42 },
  { haplogroup: 'I', ancestry: 'afr', n: 25 },
  { haplogroup: 'I', ancestry: 'amr', n: 5 },
  { haplogroup: 'I', ancestry: 'asj', n: 30 },
  { haplogroup: 'I', ancestry: 'eas', n: 1 },
  { haplogroup: 'I', ancestry: 'fin', n: 114 },
  { haplogroup: 'I', ancestry: 'nfe', n: 743 },
  { haplogroup: 'I', ancestry: 'oth', n: 8 },
  { haplogroup: 'I', ancestry: 'sas', n: 8 },
  { haplogroup: 'J', ancestry: 'afr', n: 61 },
  { haplogroup: 'J', ancestry: 'amr', n: 141 },
  { haplogroup: 'J', ancestry: 'asj', n: 107 },
  { haplogroup: 'J', ancestry: 'fin', n: 245 },
  { haplogroup: 'J', ancestry: 'mid', n: 3 },
  { haplogroup: 'J', ancestry: 'nfe', n: 2520 },
  { haplogroup: 'J', ancestry: 'oth', n: 41 },
  { haplogroup: 'J', ancestry: 'sas', n: 26 },
  { haplogroup: 'K', ancestry: 'afr', n: 52 },
  { haplogroup: 'K', ancestry: 'amr', n: 30 },
  { haplogroup: 'K', ancestry: 'asj', n: 460 },
  { haplogroup: 'K', ancestry: 'fin', n: 194 },
  { haplogroup: 'K', ancestry: 'mid', n: 1 },
  { haplogroup: 'K', ancestry: 'nfe', n: 1952 },
  { haplogroup: 'K', ancestry: 'oth', n: 33 },
  { haplogroup: 'K', ancestry: 'sas', n: 10 },
  { haplogroup: 'L0', ancestry: 'afr', n: 605 },
  { haplogroup: 'L0', ancestry: 'amr', n: 35 },
  { haplogroup: 'L0', ancestry: 'nfe', n: 10 },
  { haplogroup: 'L0', ancestry: 'oth', n: 13 },
  { haplogroup: 'L1', ancestry: 'afr', n: 2760 },
  { haplogroup: 'L1', ancestry: 'amr', n: 149 },
  { haplogroup: 'L1', ancestry: 'fin', n: 1 },
  { haplogroup: 'L1', ancestry: 'nfe', n: 28 },
  { haplogroup: 'L1', ancestry: 'oth', n: 38 },
  { haplogroup: 'L1', ancestry: 'sas', n: 1 },
  { haplogroup: 'L2', ancestry: 'afr', n: 4404 },
  { haplogroup: 'L2', ancestry: 'amr', n: 160 },
  { haplogroup: 'L2', ancestry: 'asj', n: 34 },
  { haplogroup: 'L2', ancestry: 'eas', n: 1 },
  { haplogroup: 'L2', ancestry: 'mid', n: 1 },
  { haplogroup: 'L2', ancestry: 'nfe', n: 44 },
  { haplogroup: 'L2', ancestry: 'oth', n: 78 },
  { haplogroup: 'L2', ancestry: 'sas', n: 2 },
  { haplogroup: 'L3', ancestry: 'afr', n: 5282 },
  { haplogroup: 'L3', ancestry: 'amr', n: 242 },
  { haplogroup: 'L3', ancestry: 'asj', n: 1 },
  { haplogroup: 'L3', ancestry: 'eas', n: 1 },
  { haplogroup: 'L3', ancestry: 'nfe', n: 39 },
  { haplogroup: 'L3', ancestry: 'oth', n: 104 },
  { haplogroup: 'L3', ancestry: 'sas', n: 3 },
  { haplogroup: 'L4', ancestry: 'afr', n: 118 },
  { haplogroup: 'L4', ancestry: 'amr', n: 4 },
  { haplogroup: 'L4', ancestry: 'nfe', n: 2 },
  { haplogroup: 'L4', ancestry: 'oth', n: 2 },
  { haplogroup: 'L5', ancestry: 'oth', n: 1 },
  { haplogroup: 'M', ancestry: 'afr', n: 113 },
  { haplogroup: 'M', ancestry: 'amr', n: 3 },
  { haplogroup: 'M', ancestry: 'asj', n: 10 },
  { haplogroup: 'M', ancestry: 'eas', n: 341 },
  { haplogroup: 'M', ancestry: 'fin', n: 1 },
  { haplogroup: 'M', ancestry: 'nfe', n: 64 },
  { haplogroup: 'M', ancestry: 'oth', n: 3 },
  { haplogroup: 'M', ancestry: 'sas', n: 763 },
  { haplogroup: 'N', ancestry: 'afr', n: 2 },
  { haplogroup: 'N', ancestry: 'amr', n: 1 },
  { haplogroup: 'N', ancestry: 'asj', n: 122 },
  { haplogroup: 'N', ancestry: 'eas', n: 52 },
  { haplogroup: 'N', ancestry: 'fin', n: 7 },
  { haplogroup: 'N', ancestry: 'mid', n: 1 },
  { haplogroup: 'N', ancestry: 'nfe', n: 161 },
  { haplogroup: 'N', ancestry: 'oth', n: 9 },
  { haplogroup: 'N', ancestry: 'sas', n: 11 },
  { haplogroup: 'P', ancestry: 'eas', n: 5 },
  { haplogroup: 'P', ancestry: 'nfe', n: 2 },
  { haplogroup: 'R', ancestry: 'afr', n: 5 },
  { haplogroup: 'R', ancestry: 'amr', n: 4 },
  { haplogroup: 'R', ancestry: 'asj', n: 28 },
  { haplogroup: 'R', ancestry: 'eas', n: 103 },
  { haplogroup: 'R', ancestry: 'fin', n: 29 },
  { haplogroup: 'R', ancestry: 'mid', n: 2 },
  { haplogroup: 'R', ancestry: 'nfe', n: 69 },
  { haplogroup: 'R', ancestry: 'oth', n: 4 },
  { haplogroup: 'R', ancestry: 'sas', n: 149 },
  { haplogroup: 'T', ancestry: 'afr', n: 66 },
  { haplogroup: 'T', ancestry: 'ami', n: 13 },
  { haplogroup: 'T', ancestry: 'amr', n: 34 },
  { haplogroup: 'T', ancestry: 'asj', n: 63 },
  { haplogroup: 'T', ancestry: 'fin', n: 239 },
  { haplogroup: 'T', ancestry: 'nfe', n: 2599 },
  { haplogroup: 'T', ancestry: 'oth', n: 34 },
  { haplogroup: 'T', ancestry: 'sas', n: 32 },
  { haplogroup: 'U', ancestry: 'afr', n: 185 },
  { haplogroup: 'U', ancestry: 'ami', n: 190 },
  { haplogroup: 'U', ancestry: 'amr', n: 101 },
  { haplogroup: 'U', ancestry: 'asj', n: 56 },
  { haplogroup: 'U', ancestry: 'fin', n: 1238 },
  { haplogroup: 'U', ancestry: 'mid', n: 3 },
  { haplogroup: 'U', ancestry: 'nfe', n: 3892 },
  { haplogroup: 'U', ancestry: 'oth', n: 90 },
  { haplogroup: 'U', ancestry: 'sas', n: 282 },
  { haplogroup: 'V', ancestry: 'afr', n: 16 },
  { haplogroup: 'V', ancestry: 'amr', n: 14 },
  { haplogroup: 'V', ancestry: 'asj', n: 47 },
  { haplogroup: 'V', ancestry: 'fin', n: 273 },
  { haplogroup: 'V', ancestry: 'nfe', n: 869 },
  { haplogroup: 'V', ancestry: 'oth', n: 15 },
  { haplogroup: 'W', ancestry: 'afr', n: 15 },
  { haplogroup: 'W', ancestry: 'amr', n: 6 },
  { haplogroup: 'W', ancestry: 'asj', n: 23 },
  { haplogroup: 'W', ancestry: 'fin', n: 214 },
  { haplogroup: 'W', ancestry: 'mid', n: 1 },
  { haplogroup: 'W', ancestry: 'nfe', n: 508 },
  { haplogroup: 'W', ancestry: 'oth', n: 14 },
  { haplogroup: 'W', ancestry: 'sas', n: 38 },
  { haplogroup: 'X', ancestry: 'afr', n: 11 },
  { haplogroup: 'X', ancestry: 'ami', n: 25 },
  { haplogroup: 'X', ancestry: 'amr', n: 18 },
  { haplogroup: 'X', ancestry: 'asj', n: 9 },
  { haplogroup: 'X', ancestry: 'fin', n: 59 },
  { haplogroup: 'X', ancestry: 'mid', n: 1 },
  { haplogroup: 'X', ancestry: 'nfe', n: 405 },
  { haplogroup: 'X', ancestry: 'oth', n: 7 },
  { haplogroup: 'X', ancestry: 'sas', n: 11 },
  { haplogroup: 'Y', ancestry: 'eas', n: 11 },
  { haplogroup: 'Y', ancestry: 'nfe', n: 1 },
  { haplogroup: 'Z', ancestry: 'eas', n: 28 },
  { haplogroup: 'Z', ancestry: 'fin', n: 45 },
  { haplogroup: 'Z', ancestry: 'nfe', n: 11 },
  { haplogroup: 'Z', ancestry: 'oth', n: 1 },
  { haplogroup: 'Z', ancestry: 'sas', n: 4 },
]

export default mtdnaHaplogroupSampleData
