name: Browser CI
on:
  push:
    branches:
      - main
    paths:
      - 'browser/**'
      - 'dataset-metadata/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'browser/**'
      - 'dataset-metadata/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
jobs:
  browser-checks:
    name: Browser Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.8.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '^18.17.1'
          cache: 'pnpm'
      - name: Install JS dependencies
        run: make install-js-dependencies
      - name: Check formatting
        run: make check-format-browser
      - name: Lint JS
        run: make lint-js-browser
      - name: Lint CSS
        run: make lint-css-browser
      - name: Check types
        run: make typecheck-browser
      - name: Verify clean build
        run: make build-browser
      - name: Run tests
        run: make test-browser
