name: Browser CI
on:
  push:
    branches:
      - main
    paths:
      - 'browser/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'browser/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.8.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '^18.17.1'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm eslint .
      - name: Run stylelint
        run: pnpm stylelint './**/*.(js|jsx|ts|tsx)'
      - name: Type check
        run: pnpm ts-node ./browser/build/buildHelp.ts && pnpm typecheck
      - name: Verify clean build
        run: cd browser && pnpm build
      - name: Run Jest tests
        run: pnpm jest
      - name: Install Cypress binaries
        run: pnpm cypress install
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start:browser
          wait-on: 'http://localhost:8008'
          wait-on-timeout: 150
          project: ./browser
