name: Data Pipeline CI
on:
  push:
    branches:
      - main
    paths:
      - 'data-pipeline/**'
      - 'reads/**'
      - 'development/scripts/**'
  pull_request:
    paths:
      - 'data-pipeline/**'
      - 'reads/**'
      - 'development/scripts/**'
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  data-pipeline-checks:
    name: Data Pipeline Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: make install-py-data-pipeline-dependencies
      - name: Check formatting
        run: make check-format-data-pipeline
      - name: Lint
        run: make lint-data-pipeline
      - name: Check types
        run: make typecheck-data-pipeline
