name: Data Pipeline CI
on:
  push:
    branches:
      - main
    paths:
      - 'data-pipeline/**'
      - 'reads/**'
      - 'development/scripts/**'
  pull_request:
    paths:
      - 'data-pipeline/**'
      - 'reads/**'
      - 'development/scripts/**'
      - '.github/workflows/**'
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r data-pipeline/requirements.txt
      - name: Check formatting
        run: ruff format --check data-pipeline/src/data_pipeline data-pipeline/tests data-pipeline/caids reads development/scripts
      - name: Run Ruff
        run: ruff check data-pipeline/src/data_pipeline
      - name: Run Pyright
        run: pyright --project data-pipeline
