name: Deploy scripts CI
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/deployctl/**'
  pull_request:
    paths:
      - 'deploy/deployctl/**'
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  deployctl-checks:
    name: Deployctl Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: make install-py-deploy-dependencies
      - name: Check formatting
        run: make check-format-deploy
      - name: Lint
        run: make lint-deploy
