name: Deploy scripts CI
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/deployctl/**'
  pull_request:
    paths:
      - 'deploy/deployctl/**'
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  deployctl-checks:
    name: Deployctl Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
      - name: Install dependencies
        run: make install-py-deploy-dependencies
      - name: Check formatting
        run: make check-format-deploy
      - name: Lint
        run: make lint-deploy
