name: GraphQL API CI
on:
  push:
    branches:
      - main
    paths:
      - 'graphql-api/**'
      - 'dataset-metadata/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'graphql-api/**'
      - 'dataset-metadata/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  graphql-apichecks:
    name: GraphQL API Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.8.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '^18.17.1'
          cache: 'pnpm'
      - name: Install dependencies
        run: make install-js-dependencies
      - name: Check formatting
        run: make check-format-graphql-api
      - name: Lint
        run: make lint-js-graphql-api
      - name: Check types
        run: make typecheck-graphql-api
      - name: Run tests
        run: make test-graphql-api
